# Generated by Django 3.0.1 on 2019-12-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='url_param',
            field=models.CharField(default='url', max_length=120),
        ),
    ]
