# Generated by Django 3.0.1 on 2020-01-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200111_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='avatars/default.jpg', upload_to='avatars/'),
        ),
    ]
