# Generated by Django 3.0.1 on 2019-12-30 04:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url_param', models.CharField(default='url', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Lookbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=120)),
                ('year', models.DateField()),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookbooks', to='feed.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('src', models.FileField(blank=True, upload_to='images/')),
                ('width', models.IntegerField(default=2)),
                ('height', models.IntegerField(default=3)),
                ('lookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='feed.Lookbook')),
            ],
        ),
    ]
