# Generated by Django 3.0.1 on 2019-12-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookbook',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
