# Generated by Django 3.0.1 on 2019-12-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20191230_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='height',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='picture',
            name='width',
            field=models.IntegerField(default=1),
        ),
    ]
